update package-lock and clean up .git from node modules
centrifuge/centrifuge-ethereum-contracts pull request #152
Opened 2019-06-24 08:46 UTC by rdinicut

Some npm modules contain .git folder and npm fails to build the canary build:
```
npm ERR! git /home/travis/build/centrifuge/centrifuge-ethereum-contracts/node_modules/web3-providers-ws/node_modules/websocket: Appears to be a git repo or submodule.
```

2019-06-24 08:49 UTC, xmxanuel approved these changes
LGTM

2019-06-25 08:24 UTC, pstehlik requested changes

2019-06-25 08:24 UTC, pstehlik commented on scripts/publish.js
> +        await execute(`rm -rf node_modules/**/.git`);
`find . \( -name ".git" \) -exec rm -rf -- {} +`
to avoid having the two rm statements

2019-06-26 09:21 UTC, pstehlik commented
There's a test failing on this PR. Can you check?

2019-06-26 15:14 UTC, pstehlik approved these changes

2019-06-26 19:00 UTC, merged